 # Array (Dizi) Yapısı

## İçerik
* [Arrays](#1)
* [Dynamic Array](#2)
* [Dynamic Array with Python](#3)
* [Array İş Mülakatları Soru-Cevap](#4)
* [Array Python Challenge/Problem](#5)
* [Neler Öğrendik](#6)

<a id="1"></a>
## Arrays
* Bir mesafe sensörü düşünün, her saniye bir veri gönderiyor. Bu verileri saklamak için bir değişken tanımlayabilir miyiz? Elbette, ama daha iyi bir yol var: arrays yani diziler!

* Diziler, verileri bir arada tutmamızı sağlayan yapılardır. Gerçek dünyada bu, şöyle bir şey gibi düşünülebilir: [1, 2, 3, 4, 5]. Bu, 5 elemanlı bir dizi ve her elemanın bir yeri, yani bir "indeksi" var. Örneğin, bu dizideki 2 sayısı, indeks 1'de yer alıyor.

* Python'da, tıpkı diğer programlama dillerinde olduğu gibi, dizilerdeki indeksler sıfırdan başlar. Yani, bir dizideki ilk eleman aslında "0" indeksindedir. Biz bu kurs boyunca Python kullanacağız, bu yüzden dizilerle çalışırken indekslerin sıfırdan başladığını unutmayalım!

* Diziler, sensör verileri gibi sürekli gelen bilgileri depolamak için harika bir yoldur ve Python'da bu yapı ile verilerle kolayca çalışabiliriz.

In [3]:
import numpy as np
array = np.array([[1,2,3,4,5]])  # vector 1D
print(array)
print("Boyut: ",array.shape)

[[1 2 3 4 5]]
Boyut:  (1, 5)


* Peki array tek boyulu olmak zorunda mı? Hayır 2 boyutlu hatta 3-4 boyutlu bile olabilir. (Optional: tensor is lower or higher dimensinal array)
* 2D array satır ve sütunlardan oluşur. Row - Column

In [5]:
array2D = np.array(
    [[1,2,3,4,5],
    [6,7,8,9,10]])
print(array2D)
print("boyut: ",array2D.shape)
print("2. satır 4. sütun: ",array2D[1,3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
boyut:  (2, 5)
2. satır 4. sütun:  9


<a id="2"></a>
## Dynamic Array
* Dynamic array boyutunu önceden belirtmek zorunda olmadığımız daha sonra eleman ekleyip çıkartabileceğimiz yapılara denir.
* Dynamic array growable and resizable olarak tanımlanır.
* Dynamic array neredeyse tüm programlama dillerinde çok sık kullanılan bir yapıdır.
* ![title](dynamicAr.jpg)

<a id="3"></a>
## Dynamic Array with Python
* Anlamak için kendi dynamic array class'ımızı yaratacağız.

In [9]:
import ctypes # yeni array yaratmak icin kullanacagiz

class DynamicArray(object):
    
    # initialize (constructor)
    def __init__(self):
        self.n = 0 # eleman sayisi
        self.capacity = 1 # kapasite
        self.myArray = self.make_array(self.capacity) 
        
    def __len__(self):
        """
        return array icerisinde eleman sayisi
        """
        return self.n
    
    def __getitem__(self,k):
        """
        return index k'da ki eleman(value)
        """
        if not 0 <= k < self.n:
            return IndexError("k is out of bounds !")
        
        return self.myArray[k]
        
    def append(self,eleman):
        """
        array'e eleman ekler
        """
        
        # eger kapasite dolu ise kapasiteyi iki katina cikar
        if self.n == self.capacity:
            self._resize(2*self.capacity)
            
        self.myArray[self.n] = eleman # eleman ekleme
        self.n += 1 # eleman sayisi bir arttir
        
    def _resize(self,new_cap):
        """
        array kapasitesini arttir
        """
        
        B = self.make_array(new_cap)  # yeni array yap
        
        # eski array (A) icerisindeki degerleri yeni arraye(B) icine tasi
        for k in range(self.n):
            B[k] = self.myArray[k]
        
        self.myArray = B # arrayi guncelle
        self.capacity = new_cap # kapasite guncelle
    
    def make_array(self,new_cap):
        """
        yeni array oluşturuluyor.
        """
        return (new_cap*ctypes.py_object)()
    

In [11]:
# obje tanimla
arr = DynamicArray()
# append new element 1
arr.append(1)
print(arr[0])
# append new element 1 , 3
arr.append(3)
print(arr[0],arr[1])
# append new element 1 , 3 ,5
arr.append(5)
print(arr[0],arr[1],arr[2])

1
1 3
1 3 5


<a id="4"></a>
## Array İş Mülakatları Soru-Cevap 
* Dynamic Array Neden Önemli?
    * Dynamic arrays (dinamik diziler), klasik dizilere kıyasla daha esnek bir yapı sunar. Standart diziler (arrays) sabit boyutludur, yani diziyi oluşturduğunuzda kapasitesini belirlemeniz gerekir ve sonrasında bu kapasiteyi değiştiremezsiniz. Ancak dinamik diziler, gerektiğinde otomatik olarak büyüyebilir, bu da onları veri yapılarıyla çalışırken çok kullanışlı hale getirir.

* Automatic Resizing (Otomatik Yeniden Boyutlandırma)
    * Dinamik dizilerin en büyük avantajlarından biri, boyutlarının otomatik olarak ayarlanabilmesidir. Eğer dizi dolarsa, yeni bir dizi oluşturulur ve mevcut elemanlar bu yeni diziye kopyalanır. Bu işlem genellikle dizinin kapasitesini 2 katına çıkarmak şeklinde gerçekleştirilir.

* Array ile Dynamic Array Arasındaki Farklar
    * Array (Sabit Boyutlu Dizi):
    * Sabit Boyut: Diziyi oluştururken boyutunu belirlemeniz gerekir ve bu boyut sonradan değiştirilemez.
    * Bellek Yönetimi: Bellekte sabit bir alan ayrılır.
    * Dynamic Array (Dinamik Dizi):
    * Değişken Boyut: Başlangıçta boyut belirlemeniz gerekmez; dizi doldukça otomatik olarak yeniden boyutlandırılır.
    * Esneklik: İhtiyaç duydukça dizi genişleyebilir, bu da belleği daha verimli kullanmanıza olanak tanır.
 

* Dynamic Array Avantajları ve Dezavantajları
    * Avantajlar:
    * Hızlı Erişim: Dizinin herhangi bir elemanına O(1) sürede erişebilirsiniz.
    * Esnek Boyut: Başlangıçta boyut belirlemenize gerek kalmaz ve dizi doldukça otomatik olarak genişler.
    
    * Dezavantajlar:
    * Yavaş En Kötü Durum Ekleme: Eğer dizi dolduysa, kapasitenin arttırılması gerekir, bu da zaman alıcı olabilir.
    * Maliyetli Ekleme ve Silme: Dizinin ortasına eleman eklemek veya silmek, diğer elemanların kaydırılmasını gerektirdiğinden pahalı olabilir (O(n)).

* Dynamic Array'de Boyut Nasıl Artar?
    * Genellikle kapasite dolduğunda, dinamik dizinin boyutu 2 katına çıkarılır. Bu sayede dizi genişlemeye devam ederken performans sorunları minimumda tutulur.

* İşe Alım Sorusu

* Soru: Sıralı bir veri dizisinde aşağıdaki işlemlerden hangisi O(1) değildir? (Veri elemanlarının benzersiz olduğunu varsayabilirsiniz.)

1) (A) En büyük i'inci elemanı bulmak
2) (B) Bir elemanı silmek
3) (C) En küçük i'inci elemanı bulmak
4) (D) Yukarıdakilerin hepsi





Cevap: (B) Bir elemanı silmek

1. Dynamic Array ile Stack ve Queue Arasındaki Fark Nedir?

    * Dynamic Array: Dinamik diziler, boyutları ihtiyaç oldukça otomatik olarak genişleyen veri yapılarıdır. Elemanlara rastgele erişim sağlayabilirsiniz (O(1)).
    * Stack (Yığın): Stack, LIFO (Last In, First Out) prensibiyle çalışan bir veri yapısıdır. Yani, son eklenen eleman ilk çıkar. Temel işlemler push (ekleme) ve pop (çıkarma)'dır. Rastgele erişim mümkün değildir.
    * Queue (Kuyruk): Queue, FIFO (First In, First Out) prensibiyle çalışır. İlk eklenen eleman ilk çıkar. Temel işlemler enqueue (ekleme) ve dequeue (çıkarma)'dır. Tıpkı stack gibi, rastgele erişim mümkün değildir.
    * Fark: Dinamik diziler, elemanlara rastgele erişim sağlarken, stack ve queue belirli bir sıraya göre elemanlara erişim sağlar. Ayrıca, dinamik diziler kapasite artırımı için otomatik yeniden boyutlandırılırken, stack ve queue bu mantıkta çalışmaz.

3. En Kötü Durumda Dinamik Bir Dizinin Yeniden Boyutlandırılmasının Maliyeti Nedir ve Bunu Nasıl Optimize Edebilirsiniz?
    * Cevap: En kötü durumda, dinamik bir dizinin yeniden boyutlandırılması O(n) zaman alır. Bu durumda, dizinin mevcut elemanlarını yeni bir diziye kopyalamanız gerekir. Ancak bu işlemin amortized (ortalama) maliyeti O(1) olarak kabul edilir çünkü yeniden boyutlandırma işlemi her eklemede yapılmaz, sadece dizi dolduğunda gerçekleşir. Bunu optimize etmek için kapasiteyi küçük adımlarla değil, genellikle iki katına çıkararak artırmak yaygın bir yaklaşımdır. Bu, yeniden boyutlandırma işlemlerinin sayısını minimumda tutar.

4. Veri Yapılarında Amortized Analysis Nedir? Dinamik Diziler İçin Nasıl Uygulanır?
    * Cevap: Amortized analysis, bir veri yapısında yapılan işlemlerin uzun vadede maliyetini değerlendiren bir analiz yöntemidir. Dinamik dizilerde, her ekleme işlemi anlık olarak O(1) maliyetindedir. Ancak kapasite dolduğunda ve dizi yeniden boyutlandırıldığında, bu işlem O(n) zaman alır. Amortized analysis, dizinin toplam çalışma süresini ve her bir ekleme işleminin ortalama maliyetini hesaba katar. Uzun vadede, ekleme işlemlerinin amortized maliyeti O(1) olarak kabul edilir, çünkü yeniden boyutlandırma nadir olarak gerçekleşir ve bu maliyet diğer ekleme işlemlerine yayılır.

5. Bir Dizide Ortalama O(1) Ekleme İşlemi Nasıl Sağlanır?
    * Cevap: Ortalama O(1) ekleme işlemi, genellikle dinamik dizilerde kapasiteyi iki katına çıkarma stratejisiyle sağlanır. Dizi dolduğunda, yeni ve daha büyük bir dizi oluşturulur ve eski dizideki elemanlar bu yeni diziye kopyalanır. Bu kopyalama işlemi O(n) zaman alırken, diğer ekleme işlemleri O(1) zaman alır. Uzun vadede bu işlemlerin ortalaması alındığında, her ekleme işleminin amortized maliyeti O(1) olur.

6. Python'da list Veri Yapısı Nasıl Çalışır? Dinamik Dizi Gibi mi Davranır?
    * Cevap: Evet, Python'daki list veri yapısı dinamik dizi gibi davranır. Python'da listeler, arka planda dinamik diziler olarak uygulanır. Başlangıçta sabit bir kapasiteyle oluşturulurlar, ancak kapasite dolduğunda, kapasite genellikle iki katına çıkarılarak yeniden boyutlandırılır. Bu sayede Python listeleri, eleman ekleme ve silme işlemlerinde oldukça esnektir ve performans açısından optimize edilmiştir. Yani, Python'da liste kullanırken, dinamik dizi avantajlarından yararlanabilirsiniz.

* Ekstra İpuçları:
* Veri yapılarının çalışma prensiplerini bilmek, kodunuzun performansını iyileştirmenize yardımcı olur. Örneğin, hangi veri yapısının hangi senaryoda daha verimli olduğunu anlamak, size iş görüşmelerinde artı puan kazandırabilir.
* Amortized analysis gibi konulara hakim olmak, algoritma ve veri yapısı performansını uzun vadede değerlendirme yeteneğinizi gösterir. Bu da teknik mülakatlarda dikkat çeker.

<a id="5"></a>
## Array Python Challenge/Problem
    1. Word Split

### 1) Word Split
    * input = ["deeplearning", "d,dll,a,deep,dee,base,lear,learning"]
    * output = ["deep,learning"]

In [133]:
def wordSplit(liste):
    target=liste[0]
    words=liste[1].split(",")

    for i in words:
        remainder=target[len(i):]
        if remainder in words and i in words:
            return True
    
    return "no way"


In [135]:
wordSplit(["deeplear2ning", "d,dll,a,deep,dee,base,lear,lear2ning"])

True

In [137]:
%timeit wordSplit(["deeplearning", "d,dll,a,deep,dee,base,lear,learning"])

1.76 μs ± 64.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


<a id="6"></a>
## Neler Öğrendik
* TAVSİYE: Array ile ilgili soru çözün. Mesela https://coderbyte.com/